/* jclassconfig.h.  Generated by configure.  */
/* Configuration header file for libjclass.
 *
*/

#define JCLASS_INTTYPES_H "inttypes.h"
/* #undef JCLASS_BIGENDIAN */
#define JCLASS_CURRENT 3
#define JCLASS_RELEASE 1
#define JCLASS_AGE 0
#define JCLASS_VERSION 0.5
